#!/bin/bash
#作者：book
#时间：2017/11/25
#作用：基于ssh免密登陆和/etc/hosts文件。1支持分组，2支持禁止使用命令，防止误删除

#分组
zu=(app service)
app=(app1 app2 app3)
service=(service1)


#检查参数
if [ $# -ne 2 ];then
	echo "At least 2 parameters"
	echo '-a "ls" Operate all'
	echo 'app "ls" Operate a single group'
	echo "Currently supported groups： ${zu[*]}"
	exit
fi


#不允许使用的命令
cuo=(reboot shutdown xixi) #xixi用来测试

for o in `echo ${cuo[*]}` 
do
	echo "$2" | grep -w "$o"
	if [ $? -eq 0 ];then
		echo "Not allowed to use $o"
		exit
	fi
done


#判断
r=0 #初始，如果都没匹配到则错误
t=`echo ${#zu[*]}` #总数量

if [ "$1" == "-a" ];then
	for i in `tail -n +3 /etc/hosts|awk '{print $2}'`
	do
		echo "####################server$i：####################"
		ssh $i $2
	done
else
	for p in `echo ${zu[*]}`
	do
		echo "$1" | grep -w "$p" &> /dev/null
		if [ $? -eq 0 ];then
			for u in $(eval echo \${$p[*]})
			do
				echo "####################server$u：####################"
				ssh $u $2
			done
			exit #完成后退出，不用继续循环
		else
			let r++ #失败+1，全部失败报错
		fi
	done
	[ $r -eq $t ] && echo "Incorrect group name"
fi
