#!/bin/bash
#kafka cluster




if [ "$1" == "start" ];then
	$dir/bin/kafka-server-start.sh -daemon $dir/config/server.properties
elif [ "$1" == "stop" ];then
	$dir/bin/kafka-server-stop.sh -daemon $dir/config/server.properties
elif [ "$1" == "status" ];then
    netstat -unltp | grep :${port} &> /dev/null
    [ $? -eq 0 ] && echo ok || echo no
else
	echo "start | stop | status"
fi